# test problem def 

In [1]:
import OPProblemDef as OP 

In [2]:
depot_xy , node_xy , prize = OP.get_random_problems(2 , 6 )

In [3]:
prize

tensor([[6, 5, 6, 5, 8, 3],
        [9, 8, 7, 4, 9, 6]])

In [4]:
node_xy

tensor([[[0.6621, 0.7308],
         [0.1676, 0.7511],
         [0.0975, 0.7858],
         [0.4921, 0.0807],
         [0.6772, 0.6524],
         [0.3185, 0.4541]],

        [[0.2814, 0.8638],
         [0.5290, 0.1931],
         [0.8557, 0.1836],
         [0.4277, 0.0918],
         [0.7902, 0.7151],
         [0.4692, 0.0047]]])

In [5]:
depot_xy

tensor([[[0.7993, 0.1572]],

        [[0.4959, 0.2328]]])

# test env

In [1]:
from POMO import OPEnv

In [2]:
stat_zero  = OPEnv.Reset_state()

In [5]:
stat_zero.node_xy

In [11]:
import torch

In [17]:
BATCH_IDX = torch.arange(2)[:, None].expand(2, 10)

In [18]:
BATCH_IDX

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
POMO_index = torch.arange(10)[None, :].expand(2, 10)
POMO_index

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

range(0, 4)

In [36]:
import torch

# A tensor with some singleton dimensions
t = torch.zeros(1, 2, 1, 3, 1)

# Squeezing without specifying a dimension
squeezed_t = t.squeeze()

# Squeezing a specific dimension
specific_squeeze = t.squeeze(2)

print("Original tensor shape:", t.shape)
print("Squeezed tensor shape:", squeezed_t.shape)
print("Specific squeeze shape:", specific_squeeze.shape)


Original tensor shape: torch.Size([1, 2, 1, 3, 1])
Squeezed tensor shape: torch.Size([2, 3])
Specific squeeze shape: torch.Size([1, 2, 3, 1])


In [39]:
import torch

# Example tensor
t = torch.tensor([[1, 2], [3, 4]])

# Index tensor
index = torch.tensor([[0, 1], [1, 0]])

# Gathering elements
gathered = t.gather(dim=1, index=index)

print(gathered)


tensor([[1, 2],
        [4, 3]])


In [40]:
index

tensor([[0, 1],
        [1, 0]])