# test problem def 

In [ ]:
import OPProblemDef as OP 

In [ ]:
depot_xy , node_xy , prize = OP.get_random_problems(2 , 6 )

In [ ]:
prize

In [ ]:
node_xy

In [ ]:
depot_xy

# test env

In [1]:
from POMO import OPEnv

In [2]:
env_params = {
    'problem_size': 3,
    'pomo_size': 3 }
#batch_size = 2

In [3]:
env = OPEnv.OPEnv(**env_params)

self.reset_state.depot_xy = depot_xy
self.reset_state.node_xy = node_xy
self.reset_state.node_prize = node_prize

self.step_state.BATCH_IDX = self.BATCH_IDX
self.step_state.POMO_IDX = self.POMO_IDX

## load problems


In [4]:
#batch_size = 2
env.load_problems(2)

In [5]:
env.reset_state.depot_xy

tensor([[[0.3672, 0.2785]],

        [[0.3523, 0.3545]]])

In [6]:
env.reset_state.node_xy

tensor([[[0.9233, 0.7080],
         [0.0818, 0.0269],
         [0.8004, 0.0124]],

        [[0.0549, 0.0404],
         [0.2242, 0.2826],
         [0.0987, 0.3150]]])

In [7]:
env.reset_state.node_prize

tensor([[4, 6, 6],
        [4, 7, 4]])

## reset 

In [8]:
env.reset()

(Reset_state(depot_xy=tensor([[[0.3672, 0.2785]],
 
         [[0.3523, 0.3545]]]), node_xy=tensor([[[0.9233, 0.7080],
          [0.0818, 0.0269],
          [0.8004, 0.0124]],
 
         [[0.0549, 0.0404],
          [0.2242, 0.2826],
          [0.0987, 0.3150]]]), node_prize=tensor([[4, 6, 6],
         [4, 7, 4]])),
 None,
 False)

## pre step 

In [9]:
env.pre_step()

(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=None, selected_count=0, ninf_mask=tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]), finished=tensor([[False, False, False],
         [False, False, False]])),
 None,
 False)

## step 

In [10]:
import torch


batch_size = 2
pomo_size = 3  

selected_tensor = torch.randint(1, pomo_size + 1, (batch_size, pomo_size))
selected_tensor.shape

torch.Size([2, 3])

In [11]:
selected_tensor

tensor([[2, 1, 3],
        [1, 3, 1]])

In [12]:
env.step(selected_tensor)

selected_len : tensor([[0.3805, 0.7027, 0.5085],
        [0.4325, 0.2566, 0.4325]])
remaining_len : tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
remaining_len : tensor([[0.6195, 0.2973, 0.4915],
        [0.5675, 0.7434, 0.5675]]) 


In [ ]:
env.last_node


In [ ]:
env.current_node

In [ ]:
env.prize_list

In [ ]:
env.gathering_index

In [ ]:
env.selected_prize

In [ ]:
env.ninf_mask

 check for finish 

In [ ]:
selected_tensor

In [ ]:
selected_tensor[0][0] = 1
selected_tensor[0][1] = 1
selected_tensor[0][2] = 3
selected_tensor[1][0] = 0
selected_tensor[1][1] = 1
selected_tensor[1][2] = 0

In [ ]:
selected_tensor

In [ ]:
env.step(selected_tensor)

In [ ]:
# env.ninf_mask

In [ ]:
# env.last_node

In [ ]:
# env.current_node

In [ ]:
# selected_tensor[0][0] = 1
# selected_tensor[0][1] = 1
# selected_tensor[0][2] = 3

In [ ]:
# env.step(selected_tensor)

In [ ]:
# env.ninf_mask

In [ ]:
# env.finished

In [ ]:
# selected_tensor[0][0] = 0
# selected_tensor[0][1] = 0
# selected_tensor[0][2] = 0

In [ ]:
# env.step(selected_tensor)

In [ ]:
# env.ninf_mask

In [ ]:
# env.finished

check for len too large 

In [ ]:
# env.reset()

In [ ]:
# env.pre_step()

In [ ]:
selected_tensor = torch.randint(1, pomo_size + 1, (batch_size, pomo_size))
selected_tensor

In [ ]:
# env.step(selected_tensor)

In [ ]:
# env.ninf_mask

In [ ]:
env.len_to_depot

In [ ]:
env.remaining_len

In [ ]:
env.node_xy

In [ ]:
env.last_node

# caclulate two distance node

In [13]:
selected_len = env.calculate_two_distance()

In [14]:
selected_len

tensor([[0.3805, 0.7027, 0.5085],
        [0.4325, 0.2566, 0.4325]])

In [15]:
env.node_xy_current

tensor([[[0.0818, 0.0269],
         [0.9233, 0.7080],
         [0.8004, 0.0124]],

        [[0.0549, 0.0404],
         [0.0987, 0.3150],
         [0.0549, 0.0404]]])

In [16]:
env.current_node

tensor([[2, 1, 3],
        [1, 3, 1]])

In [17]:
env.last_node

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
env.node_xy_last

In [ ]:
env.depot_node_xy

In [ ]:
env.last_node

In [ ]:
selected_len

In [ ]:
node_xy_last

In [ ]:
selected_tensor

In [ ]:
env.node_xy

In [ ]:
tensor([[3, 2, 2],
        [1, 1, 2]])

In [ ]:
node_xy_last

In [ ]:
env.depot_node_xy

## len to depot 

In [18]:
env.calculate_len_to_depot()

tensor([[0.7027, 0.3805, 0.5085],
        [0.4325, 0.1469, 0.2566]])

In [19]:
env.depot_xy_expanded

tensor([[[0.3672, 0.2785],
         [0.3672, 0.2785],
         [0.3672, 0.2785]],

        [[0.3523, 0.3545],
         [0.3523, 0.3545],
         [0.3523, 0.3545]]])

In [20]:
env.len_to_depot

tensor([[0.7027, 0.3805, 0.5085],
        [0.4325, 0.1469, 0.2566]])

# remaining len 

In [21]:
env.remaining_len

tensor([[0.6195, 0.2973, 0.4915],
        [0.5675, 0.7434, 0.5675]])

In [ ]:
selected_len

In [ ]:
env.len_to_depot

future 

In [23]:
env.calculate_future_len()

tensor([[1.0826, 1.0826, 0.0000],
        [0.0000, 0.1295, 0.2781]])

In [24]:
env.node_xy_current

tensor([[[0.0818, 0.0269],
         [0.9233, 0.7080],
         [0.8004, 0.0124]],

        [[0.0549, 0.0404],
         [0.0987, 0.3150],
         [0.0549, 0.0404]]])

In [25]:
env.node_xy

tensor([[[0.9233, 0.7080],
         [0.0818, 0.0269],
         [0.8004, 0.0124]],

        [[0.0549, 0.0404],
         [0.2242, 0.2826],
         [0.0987, 0.3150]]])

# Tut
