# test problem def 

In [21]:
import torch
import numpy as np

batch_size = 3  
problem_size = 5 
hotel_num = 3

hotel_xy = torch.rand(size=(batch_size, hotel_num ,2))
node_xy = torch.rand(size=(batch_size, problem_size, 2))
node_prize = torch.randint(1, 10, size=(batch_size, problem_size))

hotel_node_xy = torch.cat((hotel_xy, node_xy), dim=1)
# shape: (batch, problem+1, 2)
hotel_prize = torch.zeros(size=(batch_size, hotel_num))
# shape: (batch, 1)
hotel_node_prize = torch.cat((hotel_prize, node_prize), dim=1)
hotel_node_prize
# shape: (batch, problem+1)
# print(depot_node_xy)
# depot_xy
# print(node_xy,'\n', depot_xy)

tensor([[0., 0., 0., 3., 7., 5., 7., 6.],
        [0., 0., 0., 9., 3., 4., 9., 5.],
        [0., 0., 0., 9., 7., 5., 1., 8.]])

In [31]:
import torch
import numpy as np

batch_size = 3  
problem_size = 5 
hotel_num = 1

hotel_xy = torch.rand(size=(batch_size, hotel_num ,2))
node_xy = torch.rand(size=(batch_size, problem_size, 2))
hotel_xy_expanded = hotel_xy.expand_as(node_xy)
# print(hotel_xy.shape)
# print(hotel_xy,'\n',node_xy)
hotel_xy_expanded

tensor([[[0.5972, 0.1584],
         [0.5972, 0.1584],
         [0.5972, 0.1584],
         [0.5972, 0.1584],
         [0.5972, 0.1584]],

        [[0.8160, 0.6109],
         [0.8160, 0.6109],
         [0.8160, 0.6109],
         [0.8160, 0.6109],
         [0.8160, 0.6109]],

        [[0.0173, 0.7479],
         [0.0173, 0.7479],
         [0.0173, 0.7479],
         [0.0173, 0.7479],
         [0.0173, 0.7479]]])

In [56]:
import torch
import numpy as np

batch_size = 2  
problem_size = 5 
hotel_num = 5

hotel_xy = torch.rand(size=(batch_size, hotel_num ,2))
node_xy = torch.rand(size=(batch_size, problem_size, 2))

hotel_xy_expanded = hotel_xy.unsqueeze(dim=2).expand(-1,-1,problem_size,-1)
# print(hotel_xy_expanded.shape)
node_xy_expanded = node_xy.unsqueeze(dim=1).expand(-1,hotel_num,-1,-1)
# print(node_xy_expanded.shape)
# hotel_xy_expanded = hotel_xy.expand_as(node_xy)
# squared_diff = (hotel_xy_expanded - node_xy) ** 2

squared_diff = (hotel_xy_expanded - node_xy_expanded) ** 2
#shape: (batch, hotel, problem, 2)
distance_sums = torch.sum(squared_diff, dim=3)
#shape: (batch, problem)

# Square root to get the Euclidean distances
len_to_hotel = torch.sqrt(distance_sums)
# hotel_xy_expandedd = len_to_hotel.unsqueeze(dim=2).expand(-1,-1,problem_size,-1)

# hotel_xy_expandedd
len_to_hotel
# hotel_xy_expanded = hotel_xy.expand_as(node_xy)
# print(hotel_xy.shape)
# print(hotel_xy,'\n',node_xy)

# print(hotel_xy_expanded.shape)
# hotel_xy_expanded

# print(node_xy_expanded.shape)
# node_xy_expanded

tensor([[[0.3186, 0.3746, 0.4369, 0.3488, 0.4246],
         [0.7003, 0.2189, 0.6276, 0.3376, 0.8892],
         [0.3402, 0.6624, 0.1179, 0.7312, 0.9155],
         [0.0970, 0.7165, 0.2962, 0.7192, 0.6041],
         [0.7738, 0.5624, 0.9217, 0.4450, 0.3011]],

        [[0.4981, 0.5975, 0.3849, 0.2049, 0.1452],
         [0.5913, 0.3085, 1.0833, 0.6255, 0.7759],
         [0.5785, 0.7794, 0.2411, 0.3833, 0.2297],
         [0.0608, 0.5504, 0.5130, 0.3531, 0.3036],
         [0.7204, 0.9456, 0.2427, 0.5504, 0.3918]]])

In [9]:
import torch
batch_size = 1
problem_size = 5
node_prize = torch.randint(1, 10, size=(batch_size, problem_size))
print(f'befor {node_prize}\n{node_prize.shape}')
node_prize = node_prize.repeat(8, 1)
print(f'after {node_prize}\n{node_prize.shape}')

befor tensor([[3, 4, 6, 7, 7]])
torch.Size([1, 5])
after tensor([[3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7],
        [3, 4, 6, 7, 7]])
torch.Size([8, 5])


In [10]:
node_xy = torch.rand(size=(batch_size, problem_size, 2))
print(f'after {node_xy}\n{node_xy.shape}')

def augment_xy_data_by_8_fold(xy_data):
    # xy_data.shape: (batch, N, 2)

    x = xy_data[:, :, [0]]
    y = xy_data[:, :, [1]]
    # x,y shape: (batch, N, 1)

    dat1 = torch.cat((x, y), dim=2)
    dat2 = torch.cat((1 - x, y), dim=2)
    dat3 = torch.cat((x, 1 - y), dim=2)
    dat4 = torch.cat((1 - x, 1 - y), dim=2)
    dat5 = torch.cat((y, x), dim=2)
    dat6 = torch.cat((1 - y, x), dim=2)
    dat7 = torch.cat((y, 1 - x), dim=2)
    dat8 = torch.cat((1 - y, 1 - x), dim=2)

    aug_xy_data = torch.cat((dat1, dat2, dat3, dat4, dat5, dat6, dat7, dat8), dim=0)
    # shape: (8*batch, N, 2)

    return aug_xy_data

node_xy = augment_xy_data_by_8_fold(node_xy)
print(f'after {node_xy}\n{node_xy.shape}')

after tensor([[[0.2985, 0.4687],
         [0.9799, 0.1588],
         [0.5575, 0.0749],
         [0.4365, 0.3010],
         [0.2413, 0.9136]]])
torch.Size([1, 5, 2])
after tensor([[[0.2985, 0.4687],
         [0.9799, 0.1588],
         [0.5575, 0.0749],
         [0.4365, 0.3010],
         [0.2413, 0.9136]],

        [[0.7015, 0.4687],
         [0.0201, 0.1588],
         [0.4425, 0.0749],
         [0.5635, 0.3010],
         [0.7587, 0.9136]],

        [[0.2985, 0.5313],
         [0.9799, 0.8412],
         [0.5575, 0.9251],
         [0.4365, 0.6990],
         [0.2413, 0.0864]],

        [[0.7015, 0.5313],
         [0.0201, 0.8412],
         [0.4425, 0.9251],
         [0.5635, 0.6990],
         [0.7587, 0.0864]],

        [[0.4687, 0.2985],
         [0.1588, 0.9799],
         [0.0749, 0.5575],
         [0.3010, 0.4365],
         [0.9136, 0.2413]],

        [[0.5313, 0.2985],
         [0.8412, 0.9799],
         [0.9251, 0.5575],
         [0.6990, 0.4365],
         [0.0864, 0.2413]],

       

In [1]:
import OPProblemDef as OP 

In [2]:
depot_xy , node_xy , prize = OP.get_random_problems(2 , 5 )

In [3]:
prize

tensor([[8, 7, 1, 8, 5],
        [8, 1, 9, 5, 4]])

In [4]:
node_xy

tensor([[[0.7294, 0.3035],
         [0.4914, 0.2482],
         [0.0296, 0.1885],
         [0.6895, 0.5764],
         [0.7609, 0.1730]],

        [[0.5945, 0.4703],
         [0.9672, 0.4240],
         [0.8070, 0.6610],
         [0.7422, 0.8461],
         [0.0681, 0.8766]]])

In [5]:
depot_xy

tensor([[[0.3658, 0.6530]],

        [[0.6337, 0.4192]]])

# test env

In [6]:
from POMO import OPEnv

In [7]:
env_params = {
    'problem_size': 3,
    'pomo_size': 3 }
#batch_size = 2

In [8]:
env = OPEnv.OPEnv(**env_params)

self.reset_state.depot_xy = depot_xy
self.reset_state.node_xy = node_xy
self.reset_state.node_prize = node_prize

self.step_state.BATCH_IDX = self.BATCH_IDX
self.step_state.POMO_IDX = self.POMO_IDX

## load problems


In [9]:
#batch_size = 2
env.load_problems(2)

In [10]:
env.reset_state.depot_xy

tensor([[[0.6076, 0.4600]],

        [[0.1481, 0.9384]]])

In [11]:
env.reset_state.node_xy

tensor([[[0.9894, 0.9015],
         [0.2022, 0.3955],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.2468, 0.4508],
         [0.8966, 0.1446]]])

In [12]:
env.reset_state.node_prize

tensor([[5, 2, 1],
        [4, 1, 1]])

## reset 

In [13]:
env.reset()

(Reset_state(depot_xy=tensor([[[0.6076, 0.4600]],
 
         [[0.1481, 0.9384]]]), node_xy=tensor([[[0.9894, 0.9015],
          [0.2022, 0.3955],
          [0.7699, 0.9438]],
 
         [[0.4338, 0.0211],
          [0.2468, 0.4508],
          [0.8966, 0.1446]]]), node_prize=tensor([[5, 2, 1],
         [4, 1, 1]])),
 None,
 False)

## pre step 

In [14]:
env.pre_step()

(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=None, selected_count=0, ninf_mask=tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]), finished=tensor([[False, False, False],
         [False, False, False]])),
 None,
 False)

## step 

In [15]:
import torch


batch_size = 2
pomo_size = 3  

selected_tensor = torch.randint(1, pomo_size + 1, (batch_size, pomo_size))
selected_tensor.shape

torch.Size([2, 3])

In [16]:
selected_tensor

tensor([[1, 2, 2],
        [1, 2, 2]])

In [17]:
env.step(selected_tensor)

selected_len : tensor([[0.5837, 0.4105, 0.4105],
        [0.9607, 0.4974, 0.4974]])
remaining_len before step : tensor([[2., 2., 2.],
        [2., 2., 2.]]) 
remaining_len after step: tensor([[1.4163, 1.5895, 1.5895],
        [1.0393, 1.5026, 1.5026]]) 


(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=tensor([[1, 2, 2],
         [1, 2, 2]]), selected_count=1, ninf_mask=tensor([[[0., -inf, 0., 0.],
          [0., 0., -inf, 0.],
          [0., 0., -inf, 0.]],
 
         [[0., -inf, 0., -inf],
          [0., 0., -inf, -inf],
          [0., 0., -inf, -inf]]]), finished=tensor([[False, False, False],
         [False, False, False]])),
 None,
 tensor(False))

In [18]:
env.last_visited_node


tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
env.current_node

tensor([[1, 2, 2],
        [1, 2, 2]])

In [20]:
env.prize_list

tensor([[[0., 5., 2., 1.],
         [0., 5., 2., 1.],
         [0., 5., 2., 1.]],

        [[0., 4., 1., 1.],
         [0., 4., 1., 1.],
         [0., 4., 1., 1.]]])

In [21]:
env.gathering_index

tensor([[[1],
         [2],
         [2]],

        [[1],
         [2],
         [2]]])

In [22]:
env.selected_prize

tensor([[5., 2., 2.],
        [4., 1., 1.]])

In [23]:
env.ninf_mask

tensor([[[0., -inf, 0., 0.],
         [0., 0., -inf, 0.],
         [0., 0., -inf, 0.]],

        [[0., -inf, 0., -inf],
         [0., 0., -inf, -inf],
         [0., 0., -inf, -inf]]])

### check for len too large 

In [24]:
env.reset()

(Reset_state(depot_xy=tensor([[[0.6076, 0.4600]],
 
         [[0.1481, 0.9384]]]), node_xy=tensor([[[0.9894, 0.9015],
          [0.2022, 0.3955],
          [0.7699, 0.9438]],
 
         [[0.4338, 0.0211],
          [0.2468, 0.4508],
          [0.8966, 0.1446]]]), node_prize=tensor([[5, 2, 1],
         [4, 1, 1]])),
 None,
 False)

In [25]:
env.pre_step()

(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=None, selected_count=0, ninf_mask=tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]), finished=tensor([[False, False, False],
         [False, False, False]])),
 None,
 False)

In [26]:
selected_tensor = torch.randint(1, pomo_size + 1, (batch_size, pomo_size))
selected_tensor

tensor([[3, 1, 3],
        [1, 3, 1]])

In [27]:
env.step(selected_tensor)

selected_len : tensor([[0.5104, 0.5837, 0.5104],
        [0.9607, 1.0909, 0.9607]])
remaining_len before step : tensor([[2., 2., 2.],
        [2., 2., 2.]]) 
remaining_len after step: tensor([[1.4896, 1.4163, 1.4896],
        [1.0393, 0.9091, 1.0393]]) 


(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=tensor([[3, 1, 3],
         [1, 3, 1]]), selected_count=1, ninf_mask=tensor([[[0., 0., 0., -inf],
          [0., -inf, 0., 0.],
          [0., 0., 0., -inf]],
 
         [[0., -inf, 0., -inf],
          [0., -inf, -inf, -inf],
          [0., -inf, 0., -inf]]]), finished=tensor([[False, False, False],
         [False, False, False]])),
 None,
 tensor(False))

In [28]:
env.ninf_mask

tensor([[[0., 0., 0., -inf],
         [0., -inf, 0., 0.],
         [0., 0., 0., -inf]],

        [[0., -inf, 0., -inf],
         [0., -inf, -inf, -inf],
         [0., -inf, 0., -inf]]])

In [29]:
env.node_xy

tensor([[[0.9894, 0.9015],
         [0.2022, 0.3955],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.2468, 0.4508],
         [0.8966, 0.1446]]])

In [30]:
env.len_to_depot

tensor([[0.5837, 0.4105, 0.5104],
        [0.9607, 0.4974, 1.0909]])

In [31]:
env.len_to_depot_expanded

tensor([[[0.5837, 0.4105, 0.5104],
         [0.5837, 0.4105, 0.5104],
         [0.5837, 0.4105, 0.5104]],

        [[0.9607, 0.4974, 1.0909],
         [0.9607, 0.4974, 1.0909],
         [0.9607, 0.4974, 1.0909]]])

In [32]:
env.future_len

tensor([[[0.2235, 0.7892, 0.0000],
         [0.0000, 0.9358, 0.2235],
         [0.2235, 0.7892, 0.0000]],

        [[0.0000, 0.4687, 0.4789],
         [0.4789, 0.7183, 0.0000],
         [0.0000, 0.4687, 0.4789]]])

In [33]:
env.remaining_len

tensor([[1.4896, 1.4163, 1.4896],
        [1.0393, 0.9091, 1.0393]])

In [34]:
env.remaining_len_expanded

tensor([[[1.4896, 1.4896, 1.4896],
         [1.4163, 1.4163, 1.4163],
         [1.4896, 1.4896, 1.4896]],

        [[1.0393, 1.0393, 1.0393],
         [0.9091, 0.9091, 0.9091],
         [1.0393, 1.0393, 1.0393]]])

In [35]:
env.possible_dists

tensor([[[0.8073, 1.1997, 0.5104],
         [0.5837, 1.3463, 0.7339],
         [0.8073, 1.1997, 0.5104]],

        [[0.9607, 0.9661, 1.5699],
         [1.4397, 1.2157, 1.0909],
         [0.9607, 0.9661, 1.5699]]])

In [36]:
env.len_too_large

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]],

        [[False, False,  True],
         [ True,  True,  True],
         [False, False,  True]]])

In [37]:
env.len_too_large_expanded

tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False,  True],
         [False,  True,  True,  True],
         [False, False, False,  True]]])

In [38]:
env.ninf_mask

tensor([[[0., 0., 0., -inf],
         [0., -inf, 0., 0.],
         [0., 0., 0., -inf]],

        [[0., -inf, 0., -inf],
         [0., -inf, -inf, -inf],
         [0., -inf, 0., -inf]]])

### caclulate two distance node

(works fine but needs change in unsqueez method size for node_xy_current & node_xy_last_visited)

In [39]:
env.calculate_two_distance();

In [40]:
env.depot_node_xy

tensor([[[0.6076, 0.4600],
         [0.9894, 0.9015],
         [0.2022, 0.3955],
         [0.7699, 0.9438]],

        [[0.1481, 0.9384],
         [0.4338, 0.0211],
         [0.2468, 0.4508],
         [0.8966, 0.1446]]])

In [41]:
env.last_visited_node

tensor([[0, 0, 0],
        [0, 0, 0]])

In [43]:
env.current_node

tensor([[3, 1, 3],
        [1, 3, 1]])

In [44]:
env.node_xy_current

tensor([[[0.7699, 0.9438],
         [0.9894, 0.9015],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.8966, 0.1446],
         [0.4338, 0.0211]]])

In [45]:
selected_len = env.calculate_two_distance()
selected_len

tensor([[0.5104, 0.5837, 0.5104],
        [0.9607, 1.0909, 0.9607]])

In [46]:
selected_tensor

tensor([[3, 1, 3],
        [1, 3, 1]])

### len to depot 

(done and tested)

In [47]:
env.calculate_len_to_depot();
env.node_xy

tensor([[[0.9894, 0.9015],
         [0.2022, 0.3955],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.2468, 0.4508],
         [0.8966, 0.1446]]])

In [48]:
env.depot_xy_expanded

tensor([[[0.6076, 0.4600],
         [0.6076, 0.4600],
         [0.6076, 0.4600]],

        [[0.1481, 0.9384],
         [0.1481, 0.9384],
         [0.1481, 0.9384]]])

In [49]:
env.len_to_depot

tensor([[0.5837, 0.4105, 0.5104],
        [0.9607, 0.4974, 1.0909]])

### len to future

(works fine but needs change in unsqueez method size for node_xy_expanded & current_xy_expanded and dim of distance_sum)

In [50]:
env.calculate_future_len()
env.node_xy

tensor([[[0.9894, 0.9015],
         [0.2022, 0.3955],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.2468, 0.4508],
         [0.8966, 0.1446]]])

In [51]:
env.node_xy_expanded

tensor([[[[0.9894, 0.9015],
          [0.2022, 0.3955],
          [0.7699, 0.9438]],

         [[0.9894, 0.9015],
          [0.2022, 0.3955],
          [0.7699, 0.9438]],

         [[0.9894, 0.9015],
          [0.2022, 0.3955],
          [0.7699, 0.9438]]],


        [[[0.4338, 0.0211],
          [0.2468, 0.4508],
          [0.8966, 0.1446]],

         [[0.4338, 0.0211],
          [0.2468, 0.4508],
          [0.8966, 0.1446]],

         [[0.4338, 0.0211],
          [0.2468, 0.4508],
          [0.8966, 0.1446]]]])

In [52]:
env.distance_sums

tensor([[0.3407, 0.1685, 0.2605],
        [0.9230, 0.2474, 1.1901]])

In [53]:
env.node_xy_current

tensor([[[0.7699, 0.9438],
         [0.9894, 0.9015],
         [0.7699, 0.9438]],

        [[0.4338, 0.0211],
         [0.8966, 0.1446],
         [0.4338, 0.0211]]])

In [54]:
env.current_xy_expanded

tensor([[[[0.7699, 0.9438],
          [0.7699, 0.9438],
          [0.7699, 0.9438]],

         [[0.9894, 0.9015],
          [0.9894, 0.9015],
          [0.9894, 0.9015]],

         [[0.7699, 0.9438],
          [0.7699, 0.9438],
          [0.7699, 0.9438]]],


        [[[0.4338, 0.0211],
          [0.4338, 0.0211],
          [0.4338, 0.0211]],

         [[0.8966, 0.1446],
          [0.8966, 0.1446],
          [0.8966, 0.1446]],

         [[0.4338, 0.0211],
          [0.4338, 0.0211],
          [0.4338, 0.0211]]]])

In [55]:
len_to_future = env.calculate_future_len()
len_to_future

tensor([[[0.2235, 0.7892, 0.0000],
         [0.0000, 0.9358, 0.2235],
         [0.2235, 0.7892, 0.0000]],

        [[0.0000, 0.4687, 0.4789],
         [0.4789, 0.7183, 0.0000],
         [0.0000, 0.4687, 0.4789]]])

In [56]:
env.ninf_mask

tensor([[[0., 0., 0., -inf],
         [0., -inf, 0., 0.],
         [0., 0., 0., -inf]],

        [[0., -inf, 0., -inf],
         [0., -inf, -inf, -inf],
         [0., -inf, 0., -inf]]])

### check for finish and reward (done)

In [57]:
env.reset();
env.pre_step();
selected_tensor = torch.randint(1, pomo_size + 1, (batch_size, pomo_size))
selected_tensor

tensor([[1, 3, 2],
        [2, 2, 3]])

In [58]:
env.step(selected_tensor)
env.calculate_future_len()
env.calculate_len_to_depot()
env.calculate_two_distance()

selected_len : tensor([[0.5837, 0.5104, 0.4105],
        [0.4974, 0.4974, 1.0909]])
remaining_len before step : tensor([[2., 2., 2.],
        [2., 2., 2.]]) 
remaining_len after step: tensor([[1.4163, 1.4896, 1.5895],
        [1.5026, 1.5026, 0.9091]]) 


tensor([[0.5837, 0.5104, 0.4105],
        [0.4974, 0.4974, 1.0909]])

In [59]:
env.ninf_mask

tensor([[[0., -inf, 0., 0.],
         [0., 0., 0., -inf],
         [0., 0., -inf, 0.]],

        [[0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., -inf, -inf, -inf]]])

In [60]:
env.possible_dists

tensor([[[0.5837, 1.3463, 0.7339],
         [0.8073, 1.1997, 0.5104],
         [1.5195, 0.4105, 1.2996]],

        [[1.4294, 0.4974, 1.8092],
         [1.4294, 0.4974, 1.8092],
         [1.4397, 1.2157, 1.0909]]])

In [61]:
env.selected_prize

tensor([[5., 1., 2.],
        [1., 1., 1.]])

In [62]:
env.collected_prize

tensor([[5., 1., 2.],
        [1., 1., 1.]])

In [63]:
#must be changed by hands based on random selected numbers
selected_tensor[0][0] = 2
selected_tensor[0][1] = 2
selected_tensor[0][2] = 2
selected_tensor[1][0] = 2
selected_tensor[1][1] = 2
selected_tensor[1][2] = 1
selected_tensor

tensor([[2, 2, 2],
        [2, 2, 1]])

In [64]:
env.step(selected_tensor)
env.calculate_future_len()
env.calculate_len_to_depot()
env.calculate_two_distance()

selected_len : tensor([[0.9358, 0.7892, 0.0000],
        [0.0000, 0.0000, 0.4789]])
remaining_len before step : tensor([[1.4163, 1.4896, 1.5895],
        [1.5026, 1.5026, 0.9091]]) 
remaining_len after step: tensor([[0.4805, 0.7004, 1.5895],
        [1.5026, 1.5026, 0.4301]]) 


tensor([[0.9358, 0.7892, 0.0000],
        [0.0000, 0.0000, 0.4789]])

In [65]:
env.ninf_mask

tensor([[[0., -inf, -inf, -inf],
         [0., -inf, -inf, -inf],
         [0., 0., -inf, 0.]],

        [[0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., -inf, -inf, -inf]]])

In [66]:
env.possible_dists

tensor([[[1.5195, 0.4105, 1.2996],
         [1.5195, 0.4105, 1.2996],
         [1.5195, 0.4105, 1.2996]],

        [[1.4294, 0.4974, 1.8092],
         [1.4294, 0.4974, 1.8092],
         [0.9607, 0.9661, 1.5699]]])

In [67]:
env.selected_prize

tensor([[2., 2., 2.],
        [1., 1., 4.]])

In [68]:
env.collected_prize

tensor([[7., 3., 4.],
        [2., 2., 5.]])

In [69]:
#must be changed by hands based on random selected numbers
selected_tensor[0][0] = 1
selected_tensor[0][1] = 3
selected_tensor[0][2] = 1
selected_tensor[1][0] = 0
selected_tensor[1][1] = 0
selected_tensor[1][2] = 0
selected_tensor

tensor([[1, 3, 1],
        [0, 0, 0]])

In [70]:
env.step(selected_tensor)
env.calculate_future_len()
env.calculate_len_to_depot()
env.calculate_two_distance()

selected_len : tensor([[0.9358, 0.7892, 0.9358],
        [0.4974, 0.4974, 0.9607]])
remaining_len before step : tensor([[0.4805, 0.7004, 1.5895],
        [1.5026, 1.5026, 0.4301]]) 
remaining_len after step: tensor([[-0.4553, -0.0888,  0.6537],
        [ 1.0052,  1.0052, -0.5306]]) 


tensor([[0.9358, 0.7892, 0.9358],
        [0.4974, 0.4974, 0.9607]])

In [71]:
env.ninf_mask

tensor([[[0., -inf, -inf, -inf],
         [0., -inf, -inf, -inf],
         [0., -inf, -inf, -inf]],

        [[-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf]]])

In [72]:
env.newly_finished

tensor([[False, False, False],
        [ True,  True,  True]])

In [73]:
env.finished

tensor([[False, False, False],
        [ True,  True,  True]])

In [74]:
env.selected_prize

tensor([[5., 1., 5.],
        [0., 0., 0.]])

In [75]:
env.collected_prize

tensor([[12.,  4.,  9.],
        [ 2.,  2.,  5.]])

In [76]:
#must be changed by hands based on random selected numbers
selected_tensor[0][0] = 0
selected_tensor[0][1] = 0
selected_tensor[0][2] = 0
selected_tensor[1][0] = 0
selected_tensor[1][1] = 0
selected_tensor[1][2] = 0
selected_tensor

tensor([[0, 0, 0],
        [0, 0, 0]])

In [77]:
env.step(selected_tensor)

selected_len : tensor([[0.5837, 0.5104, 0.5837],
        [0.0000, 0.0000, 0.0000]])
remaining_len before step : tensor([[-0.4553, -0.0888,  0.6537],
        [ 1.0052,  1.0052, -0.5306]]) 
remaining_len after step: tensor([[-1.0390, -0.5992,  0.0700],
        [ 1.0052,  1.0052, -0.5306]]) 


(Step_state(BATCH_IDX=tensor([[0, 0, 0],
         [1, 1, 1]]), POMO_IDX=tensor([[0, 1, 2],
         [0, 1, 2]]), current_node=tensor([[0, 0, 0],
         [0, 0, 0]]), selected_count=4, ninf_mask=tensor([[[-inf, -inf, -inf, -inf],
          [-inf, -inf, -inf, -inf],
          [-inf, -inf, -inf, -inf]],
 
         [[-inf, -inf, -inf, -inf],
          [-inf, -inf, -inf, -inf],
          [-inf, -inf, -inf, -inf]]]), finished=tensor([[True, True, True],
         [True, True, True]])),
 tensor([[12.,  4.,  9.],
         [ 2.,  2.,  5.]]),
 tensor(True))

In [78]:
env.ninf_mask

tensor([[[-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf]],

        [[-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf]]])